# Generated by Django 4.2.2 on 2023-06-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='pdf', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GestionDocumentos',
            fields=[
                ('gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('docente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelo.docente')),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.documento')),
                ('estudiante_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=105, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='resultados/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.gestiondocumentos')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.usuario'),
        ),
    ]
