# Generated by Django 4.2.2 on 2023-06-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='gestiondocumentos',
            old_name='docente_id',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='gestiondocumentos',
            old_name='documento_id',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='gestiondocumentos',
            old_name='estudiante_id',
            new_name='estudiante',
        ),
    ]
