# Generated by Django 4.2.2 on 2023-07-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_gestiondocumentos_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestiondocumentos',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelo.docente'),
        ),
    ]
