# Generated by Django 4.2.2 on 2023-07-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_usuario_autorizado_alter_gestiondocumentos_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='ejecutando',
            field=models.BooleanField(default=False),
        ),
    ]
